## BiesTimer v 0.3
## Created by Alex Bies
## Coded by Jon Clucas
## Copyleft 2008 by Bad Mutha Booboisie Software under GPLv3
## This is free software, and you are welcome to redistribute it under certain conditions;
## see http://www.gnu.org/licenses/gpl-3.0.txt for details.

BiesOpenFieldTimer : learning.c
	g++ -o BiesOpenFieldTimer learning.c
clean :
	rm -f a.out BiesOpenFieldTimer BiesTimer BiesOpenFieldTimer.tar BiesTimer.tar *~
tar :
	tar -cvf BiesOpenFieldTimer.tar learning.c README.txt Makefile
